package gui;

import java.awt.Font;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBoxMenuItem;
import model.*;

/**
 *
 * @author tadaki
 */
public class MainFrame extends javax.swing.JFrame {

    private AbstractChaosMap sys = null;
    private ButtonGroup radiusGroup;
    private final Font font;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        sys = new Mandelbrot(drawPanel.getPreferredSize());
        drawPanel.addGuiEventListener(evt -> guiChanged(evt));
        font = new Font("Yu Gothic UI", 0, 24);
        setRadiusMenu();
    }

    private void setRadiusMenu() {
        List<Double> dList = new ArrayList<>();
        int k = 6;
        double r = 2.;
        for (int i = 0; i < k; i++) {
            dList.add(r);
            r *= 4;
        }
        radiusGroup = new ButtonGroup();
        for (double d : dList) {
            JCheckBoxMenuItem item = new JCheckBoxMenuItem(String.valueOf(d));
            item.addActionListener(evt -> sys.setRadius(d));
            item.setFont(font);
            radiusMenu.add(item);
            radiusGroup.add(item);
        }
        {
            double d = 2.;
            JCheckBoxMenuItem item = new JCheckBoxMenuItem("reset");
            item.addActionListener(evt -> sys.setRadius(d));
            item.setFont(font);
            radiusMenu.add(item);
            radiusGroup.add(item);
        }

    }

    public void guiChanged(GuiEvent evt) {
        if (sys == null) {
            return;
        }
        switch (evt.getEventType()) {
            case NewArea ->
                sys.selectArea(evt.getRect());
            case SetCenter ->
                sys.selectCenter(evt.getPoint());
            default -> {
            }
        }
        drawActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawPanel = new gui.DrawPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();
        actionMenu = new javax.swing.JMenu();
        draw = new javax.swing.JMenuItem();
        resetArea = new javax.swing.JMenuItem();
        radiusMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mandelbrot Set");
        setResizable(false);

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));
        drawPanel.setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        getContentPane().add(drawPanel, java.awt.BorderLayout.CENTER);

        menuBar.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        quit.setBackground(new java.awt.Color(255, 204, 204));
        quit.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        quit.setText("quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        fileMenu.add(quit);

        menuBar.add(fileMenu);

        actionMenu.setText("Draw");
        actionMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N

        draw.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        draw.setText("draw");
        draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawActionPerformed(evt);
            }
        });
        actionMenu.add(draw);

        resetArea.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        resetArea.setText("resetArea");
        resetArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAreaActionPerformed(evt);
            }
        });
        actionMenu.add(resetArea);

        menuBar.add(actionMenu);

        radiusMenu.setText("Radius");
        radiusMenu.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        menuBar.add(radiusMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawActionPerformed
        sys.initImage();
        BufferedImage image = sys.createImage();
        drawPanel.setImgage(image);
        drawPanel.clearRect();
    }//GEN-LAST:event_drawActionPerformed

    private void resetAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAreaActionPerformed
        sys.resetArea();
        sys.initImage();
        BufferedImage image = sys.createImage();
        drawPanel.setImgage(image);
    }//GEN-LAST:event_resetAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actionMenu;
    private javax.swing.JMenuItem draw;
    private gui.DrawPanel drawPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem quit;
    private javax.swing.JMenu radiusMenu;
    private javax.swing.JMenuItem resetArea;
    // End of variables declaration//GEN-END:variables
}
